package messaging

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"sync"
	"time"

	"github.com/google/uuid"
)

// PendingRequest tracks an in-flight request awaiting a response
type PendingRequest struct {
	RequestID   string
	Type        string
	SourceID    string        // Dashboard user ID that initiated the request
	TargetID    string        // Agent ID that should respond
	SessionID   string        // Optional session context
	DeviceID    string        // Optional device context
	CreatedAt   time.Time
	ExpiresAt   time.Time
	Response    chan *MessageEnvelope
	Cancel      context.CancelFunc
	Metadata    map[string]interface{}
}

// PendingRequestManager tracks pending requests and routes responses back to requesters.
// It provides request/response correlation, timeout handling, and cleanup on disconnect.
type PendingRequestManager struct {
	mu       sync.RWMutex
	requests map[string]*PendingRequest // requestId -> request

	// Indexes for efficient lookup
	bySource map[string]map[string]bool // sourceId -> set of requestIds
	byTarget map[string]map[string]bool // targetId -> set of requestIds

	// Configuration
	defaultTimeout time.Duration

	// Metrics
	totalRequests   int64
	totalResponses  int64
	totalTimeouts   int64
	totalCancelled  int64
}

// NewPendingRequestManager creates a new manager with the specified default timeout
func NewPendingRequestManager(defaultTimeout time.Duration) *PendingRequestManager {
	if defaultTimeout <= 0 {
		defaultTimeout = 30 * time.Second
	}

	mgr := &PendingRequestManager{
		requests:       make(map[string]*PendingRequest),
		bySource:       make(map[string]map[string]bool),
		byTarget:       make(map[string]map[string]bool),
		defaultTimeout: defaultTimeout,
	}

	// Start cleanup goroutine
	go mgr.cleanupLoop()

	return mgr
}

// RegisterRequest creates a new pending request and returns a channel to receive the response.
// The caller should use the channel with a select statement or read with timeout.
func (m *PendingRequestManager) RegisterRequest(
	msgType string,
	sourceID string,
	targetID string,
	timeout time.Duration,
) (*PendingRequest, error) {
	if timeout <= 0 {
		timeout = m.defaultTimeout
	}

	requestID := uuid.New().String()
	ctx, cancel := context.WithTimeout(context.Background(), timeout)

	req := &PendingRequest{
		RequestID:  requestID,
		Type:       msgType,
		SourceID:   sourceID,
		TargetID:   targetID,
		CreatedAt:  time.Now(),
		ExpiresAt:  time.Now().Add(timeout),
		Response:   make(chan *MessageEnvelope, 1),
		Cancel:     cancel,
		Metadata:   make(map[string]interface{}),
	}

	m.mu.Lock()
	m.requests[requestID] = req

	// Index by source
	if m.bySource[sourceID] == nil {
		m.bySource[sourceID] = make(map[string]bool)
	}
	m.bySource[sourceID][requestID] = true

	// Index by target
	if m.byTarget[targetID] == nil {
		m.byTarget[targetID] = make(map[string]bool)
	}
	m.byTarget[targetID][requestID] = true

	m.totalRequests++
	m.mu.Unlock()

	// Start timeout goroutine
	go func() {
		<-ctx.Done()
		m.completeRequest(requestID, nil, true)
	}()

	return req, nil
}

// RegisterRequestWithID registers a request with a pre-existing ID
// (useful when the ID is generated by the frontend)
func (m *PendingRequestManager) RegisterRequestWithID(
	requestID string,
	msgType string,
	sourceID string,
	targetID string,
	timeout time.Duration,
) (*PendingRequest, error) {
	if timeout <= 0 {
		timeout = m.defaultTimeout
	}

	m.mu.Lock()
	if _, exists := m.requests[requestID]; exists {
		m.mu.Unlock()
		return nil, fmt.Errorf("request ID already exists: %s", requestID)
	}
	m.mu.Unlock()

	ctx, cancel := context.WithTimeout(context.Background(), timeout)

	req := &PendingRequest{
		RequestID:  requestID,
		Type:       msgType,
		SourceID:   sourceID,
		TargetID:   targetID,
		CreatedAt:  time.Now(),
		ExpiresAt:  time.Now().Add(timeout),
		Response:   make(chan *MessageEnvelope, 1),
		Cancel:     cancel,
		Metadata:   make(map[string]interface{}),
	}

	m.mu.Lock()
	m.requests[requestID] = req

	// Index by source
	if m.bySource[sourceID] == nil {
		m.bySource[sourceID] = make(map[string]bool)
	}
	m.bySource[sourceID][requestID] = true

	// Index by target
	if m.byTarget[targetID] == nil {
		m.byTarget[targetID] = make(map[string]bool)
	}
	m.byTarget[targetID][requestID] = true

	m.totalRequests++
	m.mu.Unlock()

	// Start timeout goroutine
	go func() {
		<-ctx.Done()
		m.completeRequest(requestID, nil, true)
	}()

	return req, nil
}

// HandleResponse routes an incoming response to its pending request
func (m *PendingRequestManager) HandleResponse(env *MessageEnvelope) bool {
	if env.RequestID == "" {
		return false
	}

	m.mu.RLock()
	_, exists := m.requests[env.RequestID]
	m.mu.RUnlock()

	if !exists {
		log.Printf("[PendingRequests] No pending request for ID: %s (may have timed out)", env.RequestID)
		return false
	}

	return m.completeRequest(env.RequestID, env, false)
}

// completeRequest removes the request from pending and sends the response
func (m *PendingRequestManager) completeRequest(requestID string, response *MessageEnvelope, isTimeout bool) bool {
	m.mu.Lock()
	req, exists := m.requests[requestID]
	if !exists {
		m.mu.Unlock()
		return false
	}

	// Remove from maps
	delete(m.requests, requestID)
	if m.bySource[req.SourceID] != nil {
		delete(m.bySource[req.SourceID], requestID)
		if len(m.bySource[req.SourceID]) == 0 {
			delete(m.bySource, req.SourceID)
		}
	}
	if m.byTarget[req.TargetID] != nil {
		delete(m.byTarget[req.TargetID], requestID)
		if len(m.byTarget[req.TargetID]) == 0 {
			delete(m.byTarget, req.TargetID)
		}
	}

	if isTimeout {
		m.totalTimeouts++
	} else {
		m.totalResponses++
	}
	m.mu.Unlock()

	// Cancel the timeout context
	req.Cancel()

	// Send response (non-blocking)
	if response != nil {
		select {
		case req.Response <- response:
		default:
			// Channel full or closed, response dropped
			log.Printf("[PendingRequests] Dropped response for %s (channel full)", requestID)
		}
	}
	close(req.Response)

	return true
}

// CancelRequest cancels a specific pending request
func (m *PendingRequestManager) CancelRequest(requestID string) bool {
	m.mu.Lock()
	if _, exists := m.requests[requestID]; !exists {
		m.mu.Unlock()
		return false
	}
	m.totalCancelled++
	m.mu.Unlock()

	return m.completeRequest(requestID, nil, false)
}

// CancelBySource cancels all pending requests from a specific source (e.g., on dashboard disconnect)
func (m *PendingRequestManager) CancelBySource(sourceID string) int {
	m.mu.RLock()
	requestIDs := make([]string, 0)
	if ids, ok := m.bySource[sourceID]; ok {
		for id := range ids {
			requestIDs = append(requestIDs, id)
		}
	}
	m.mu.RUnlock()

	cancelled := 0
	for _, id := range requestIDs {
		if m.CancelRequest(id) {
			cancelled++
		}
	}

	if cancelled > 0 {
		log.Printf("[PendingRequests] Cancelled %d requests for source %s", cancelled, sourceID)
	}

	return cancelled
}

// CancelByTarget cancels all pending requests targeting a specific agent (e.g., on agent disconnect)
func (m *PendingRequestManager) CancelByTarget(targetID string) int {
	m.mu.RLock()
	requestIDs := make([]string, 0)
	if ids, ok := m.byTarget[targetID]; ok {
		for id := range ids {
			requestIDs = append(requestIDs, id)
		}
	}
	m.mu.RUnlock()

	cancelled := 0
	for _, id := range requestIDs {
		if m.CancelRequest(id) {
			cancelled++
		}
	}

	if cancelled > 0 {
		log.Printf("[PendingRequests] Cancelled %d requests for target %s", cancelled, targetID)
	}

	return cancelled
}

// GetPending returns information about a pending request (for debugging)
func (m *PendingRequestManager) GetPending(requestID string) (*PendingRequest, bool) {
	m.mu.RLock()
	defer m.mu.RUnlock()
	req, ok := m.requests[requestID]
	return req, ok
}

// GetPendingCount returns the number of pending requests
func (m *PendingRequestManager) GetPendingCount() int {
	m.mu.RLock()
	defer m.mu.RUnlock()
	return len(m.requests)
}

// GetMetrics returns metrics about request handling
func (m *PendingRequestManager) GetMetrics() map[string]interface{} {
	m.mu.RLock()
	defer m.mu.RUnlock()
	return map[string]interface{}{
		"pending":    len(m.requests),
		"total":      m.totalRequests,
		"responses":  m.totalResponses,
		"timeouts":   m.totalTimeouts,
		"cancelled":  m.totalCancelled,
		"bySource":   len(m.bySource),
		"byTarget":   len(m.byTarget),
	}
}

// cleanupLoop periodically cleans up expired requests
func (m *PendingRequestManager) cleanupLoop() {
	ticker := time.NewTicker(10 * time.Second)
	defer ticker.Stop()

	for range ticker.C {
		m.cleanup()
	}
}

// cleanup removes requests that have expired but weren't caught by their timeout
func (m *PendingRequestManager) cleanup() {
	now := time.Now()
	var expired []string

	m.mu.RLock()
	for id, req := range m.requests {
		// Add grace period beyond expiration
		if now.After(req.ExpiresAt.Add(5 * time.Second)) {
			expired = append(expired, id)
		}
	}
	m.mu.RUnlock()

	for _, id := range expired {
		m.completeRequest(id, nil, true)
	}

	if len(expired) > 0 {
		log.Printf("[PendingRequests] Cleaned up %d expired requests", len(expired))
	}
}

// AwaitResponse waits for a response with the given timeout.
// Returns the response envelope, or an error on timeout/cancellation.
func (m *PendingRequestManager) AwaitResponse(req *PendingRequest) (*MessageEnvelope, error) {
	select {
	case response, ok := <-req.Response:
		if !ok {
			return nil, fmt.Errorf("request cancelled or timed out")
		}
		if response == nil {
			return nil, fmt.Errorf("request timed out")
		}
		return response, nil
	}
}

// SendAndWait is a convenience method that sends a message and waits for its response.
// The sendFn is called to actually send the message after the request is registered.
func (m *PendingRequestManager) SendAndWait(
	msgType string,
	sourceID string,
	targetID string,
	timeout time.Duration,
	sendFn func(requestID string) error,
) (*MessageEnvelope, error) {
	req, err := m.RegisterRequest(msgType, sourceID, targetID, timeout)
	if err != nil {
		return nil, fmt.Errorf("failed to register request: %w", err)
	}

	if err := sendFn(req.RequestID); err != nil {
		m.CancelRequest(req.RequestID)
		return nil, fmt.Errorf("failed to send message: %w", err)
	}

	return m.AwaitResponse(req)
}

// TimeoutError represents a request that timed out
type TimeoutError struct {
	RequestID string
	Duration  time.Duration
}

func (e *TimeoutError) Error() string {
	return fmt.Sprintf("request %s timed out after %v", e.RequestID, e.Duration)
}

// ResponsePayload extracts the payload from a response envelope
func ResponsePayload(env *MessageEnvelope) (success bool, data json.RawMessage, errMsg string, err error) {
	if env == nil {
		return false, nil, "", fmt.Errorf("nil envelope")
	}

	var response struct {
		Success bool            `json:"success"`
		Data    json.RawMessage `json:"data"`
		Error   string          `json:"error"`
	}

	if err := json.Unmarshal(env.Payload, &response); err != nil {
		return false, nil, "", fmt.Errorf("failed to parse response payload: %w", err)
	}

	return response.Success, response.Data, response.Error, nil
}
