// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: dataplane.proto

package dataplane

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// System metrics streamed from agent
type Metrics struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentId         string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp       int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CpuPercent      float64                `protobuf:"fixed64,3,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryPercent   float64                `protobuf:"fixed64,4,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	MemoryUsed      uint64                 `protobuf:"varint,5,opt,name=memory_used,json=memoryUsed,proto3" json:"memory_used,omitempty"`
	MemoryAvailable uint64                 `protobuf:"varint,6,opt,name=memory_available,json=memoryAvailable,proto3" json:"memory_available,omitempty"`
	DiskPercent     float64                `protobuf:"fixed64,7,opt,name=disk_percent,json=diskPercent,proto3" json:"disk_percent,omitempty"`
	DiskUsed        uint64                 `protobuf:"varint,8,opt,name=disk_used,json=diskUsed,proto3" json:"disk_used,omitempty"`
	DiskTotal       uint64                 `protobuf:"varint,9,opt,name=disk_total,json=diskTotal,proto3" json:"disk_total,omitempty"`
	NetworkRxBytes  uint64                 `protobuf:"varint,10,opt,name=network_rx_bytes,json=networkRxBytes,proto3" json:"network_rx_bytes,omitempty"`
	NetworkTxBytes  uint64                 `protobuf:"varint,11,opt,name=network_tx_bytes,json=networkTxBytes,proto3" json:"network_tx_bytes,omitempty"`
	ProcessCount    int32                  `protobuf:"varint,12,opt,name=process_count,json=processCount,proto3" json:"process_count,omitempty"`
	Uptime          uint64                 `protobuf:"varint,13,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_dataplane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{0}
}

func (x *Metrics) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Metrics) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Metrics) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *Metrics) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *Metrics) GetMemoryUsed() uint64 {
	if x != nil {
		return x.MemoryUsed
	}
	return 0
}

func (x *Metrics) GetMemoryAvailable() uint64 {
	if x != nil {
		return x.MemoryAvailable
	}
	return 0
}

func (x *Metrics) GetDiskPercent() float64 {
	if x != nil {
		return x.DiskPercent
	}
	return 0
}

func (x *Metrics) GetDiskUsed() uint64 {
	if x != nil {
		return x.DiskUsed
	}
	return 0
}

func (x *Metrics) GetDiskTotal() uint64 {
	if x != nil {
		return x.DiskTotal
	}
	return 0
}

func (x *Metrics) GetNetworkRxBytes() uint64 {
	if x != nil {
		return x.NetworkRxBytes
	}
	return 0
}

func (x *Metrics) GetNetworkTxBytes() uint64 {
	if x != nil {
		return x.NetworkTxBytes
	}
	return 0
}

func (x *Metrics) GetProcessCount() int32 {
	if x != nil {
		return x.ProcessCount
	}
	return 0
}

func (x *Metrics) GetUptime() uint64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

// System information for inventory
type SystemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	OsVersion     string                 `protobuf:"bytes,3,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	Platform      string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	Architecture  string                 `protobuf:"bytes,5,opt,name=architecture,proto3" json:"architecture,omitempty"`
	CpuModel      string                 `protobuf:"bytes,6,opt,name=cpu_model,json=cpuModel,proto3" json:"cpu_model,omitempty"`
	CpuCores      int32                  `protobuf:"varint,7,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	CpuThreads    int32                  `protobuf:"varint,8,opt,name=cpu_threads,json=cpuThreads,proto3" json:"cpu_threads,omitempty"`
	CpuSpeed      float64                `protobuf:"fixed64,9,opt,name=cpu_speed,json=cpuSpeed,proto3" json:"cpu_speed,omitempty"`
	TotalMemory   uint64                 `protobuf:"varint,10,opt,name=total_memory,json=totalMemory,proto3" json:"total_memory,omitempty"`
	Gpu           []*GPUInfo             `protobuf:"bytes,11,rep,name=gpu,proto3" json:"gpu,omitempty"`
	Storage       []*StorageInfo         `protobuf:"bytes,12,rep,name=storage,proto3" json:"storage,omitempty"`
	SerialNumber  string                 `protobuf:"bytes,13,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	Manufacturer  string                 `protobuf:"bytes,14,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Model         string                 `protobuf:"bytes,15,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfo) Reset() {
	*x = SystemInfo{}
	mi := &file_dataplane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo) ProtoMessage() {}

func (x *SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo.ProtoReflect.Descriptor instead.
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{1}
}

func (x *SystemInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SystemInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *SystemInfo) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *SystemInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *SystemInfo) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *SystemInfo) GetCpuModel() string {
	if x != nil {
		return x.CpuModel
	}
	return ""
}

func (x *SystemInfo) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *SystemInfo) GetCpuThreads() int32 {
	if x != nil {
		return x.CpuThreads
	}
	return 0
}

func (x *SystemInfo) GetCpuSpeed() float64 {
	if x != nil {
		return x.CpuSpeed
	}
	return 0
}

func (x *SystemInfo) GetTotalMemory() uint64 {
	if x != nil {
		return x.TotalMemory
	}
	return 0
}

func (x *SystemInfo) GetGpu() []*GPUInfo {
	if x != nil {
		return x.Gpu
	}
	return nil
}

func (x *SystemInfo) GetStorage() []*StorageInfo {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *SystemInfo) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *SystemInfo) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *SystemInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type GPUInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Vendor        string                 `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Memory        uint64                 `protobuf:"varint,3,opt,name=memory,proto3" json:"memory,omitempty"`
	DriverVersion string                 `protobuf:"bytes,4,opt,name=driver_version,json=driverVersion,proto3" json:"driver_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPUInfo) Reset() {
	*x = GPUInfo{}
	mi := &file_dataplane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUInfo) ProtoMessage() {}

func (x *GPUInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUInfo.ProtoReflect.Descriptor instead.
func (*GPUInfo) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{2}
}

func (x *GPUInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GPUInfo) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *GPUInfo) GetMemory() uint64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *GPUInfo) GetDriverVersion() string {
	if x != nil {
		return x.DriverVersion
	}
	return ""
}

type StorageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Mountpoint    string                 `protobuf:"bytes,2,opt,name=mountpoint,proto3" json:"mountpoint,omitempty"`
	FsType        string                 `protobuf:"bytes,3,opt,name=fs_type,json=fsType,proto3" json:"fs_type,omitempty"`
	Total         uint64                 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Used          uint64                 `protobuf:"varint,5,opt,name=used,proto3" json:"used,omitempty"`
	Free          uint64                 `protobuf:"varint,6,opt,name=free,proto3" json:"free,omitempty"`
	Percent       float64                `protobuf:"fixed64,7,opt,name=percent,proto3" json:"percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageInfo) Reset() {
	*x = StorageInfo{}
	mi := &file_dataplane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageInfo) ProtoMessage() {}

func (x *StorageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageInfo.ProtoReflect.Descriptor instead.
func (*StorageInfo) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{3}
}

func (x *StorageInfo) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *StorageInfo) GetMountpoint() string {
	if x != nil {
		return x.Mountpoint
	}
	return ""
}

func (x *StorageInfo) GetFsType() string {
	if x != nil {
		return x.FsType
	}
	return ""
}

func (x *StorageInfo) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *StorageInfo) GetUsed() uint64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *StorageInfo) GetFree() uint64 {
	if x != nil {
		return x.Free
	}
	return 0
}

func (x *StorageInfo) GetPercent() float64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

type InstalledSoftware struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Publisher     string                 `protobuf:"bytes,3,opt,name=publisher,proto3" json:"publisher,omitempty"`
	InstallDate   string                 `protobuf:"bytes,4,opt,name=install_date,json=installDate,proto3" json:"install_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstalledSoftware) Reset() {
	*x = InstalledSoftware{}
	mi := &file_dataplane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstalledSoftware) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstalledSoftware) ProtoMessage() {}

func (x *InstalledSoftware) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstalledSoftware.ProtoReflect.Descriptor instead.
func (*InstalledSoftware) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{4}
}

func (x *InstalledSoftware) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InstalledSoftware) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InstalledSoftware) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *InstalledSoftware) GetInstallDate() string {
	if x != nil {
		return x.InstallDate
	}
	return ""
}

// Inventory data upload
type InventoryData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SystemInfo    *SystemInfo            `protobuf:"bytes,3,opt,name=system_info,json=systemInfo,proto3" json:"system_info,omitempty"`
	Software      []*InstalledSoftware   `protobuf:"bytes,4,rep,name=software,proto3" json:"software,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryData) Reset() {
	*x = InventoryData{}
	mi := &file_dataplane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryData) ProtoMessage() {}

func (x *InventoryData) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryData.ProtoReflect.Descriptor instead.
func (*InventoryData) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{5}
}

func (x *InventoryData) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *InventoryData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *InventoryData) GetSystemInfo() *SystemInfo {
	if x != nil {
		return x.SystemInfo
	}
	return nil
}

func (x *InventoryData) GetSoftware() []*InstalledSoftware {
	if x != nil {
		return x.Software
	}
	return nil
}

// Log entry for streaming
type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         string                 `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_dataplane_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{6}
}

func (x *LogEntry) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *LogEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Batch of log entries
type LogBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Entries       []*LogEntry            `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogBatch) Reset() {
	*x = LogBatch{}
	mi := &file_dataplane_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogBatch) ProtoMessage() {}

func (x *LogBatch) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogBatch.ProtoReflect.Descriptor instead.
func (*LogBatch) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{7}
}

func (x *LogBatch) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *LogBatch) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// File chunk for streaming file content
type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	FilePath      string                 `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Offset        int64                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	TotalSize     int64                  `protobuf:"varint,6,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	IsLast        bool                   `protobuf:"varint,7,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_dataplane_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{8}
}

func (x *FileChunk) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *FileChunk) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FileChunk) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FileChunk) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *FileChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

// Bulk data chunk for diagnostics
type BulkDataChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	DataType      string                 `protobuf:"bytes,3,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	ChunkIndex    int32                  `protobuf:"varint,5,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	TotalChunks   int32                  `protobuf:"varint,6,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	IsLast        bool                   `protobuf:"varint,7,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkDataChunk) Reset() {
	*x = BulkDataChunk{}
	mi := &file_dataplane_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkDataChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkDataChunk) ProtoMessage() {}

func (x *BulkDataChunk) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkDataChunk.ProtoReflect.Descriptor instead.
func (*BulkDataChunk) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{9}
}

func (x *BulkDataChunk) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *BulkDataChunk) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *BulkDataChunk) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *BulkDataChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BulkDataChunk) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *BulkDataChunk) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *BulkDataChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

// Generic response
type StreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_dataplane_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{10}
}

func (x *StreamResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StreamResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Empty message for streams that don't need request data
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_dataplane_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{11}
}

var File_dataplane_proto protoreflect.FileDescriptor

const file_dataplane_proto_rawDesc = "" +
	"\n" +
	"\x0fdataplane.proto\x12\x12sentinel.dataplane\"\xc6\x03\n" +
	"\aMetrics\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vcpu_percent\x18\x03 \x01(\x01R\n" +
	"cpuPercent\x12%\n" +
	"\x0ememory_percent\x18\x04 \x01(\x01R\rmemoryPercent\x12\x1f\n" +
	"\vmemory_used\x18\x05 \x01(\x04R\n" +
	"memoryUsed\x12)\n" +
	"\x10memory_available\x18\x06 \x01(\x04R\x0fmemoryAvailable\x12!\n" +
	"\fdisk_percent\x18\a \x01(\x01R\vdiskPercent\x12\x1b\n" +
	"\tdisk_used\x18\b \x01(\x04R\bdiskUsed\x12\x1d\n" +
	"\n" +
	"disk_total\x18\t \x01(\x04R\tdiskTotal\x12(\n" +
	"\x10network_rx_bytes\x18\n" +
	" \x01(\x04R\x0enetworkRxBytes\x12(\n" +
	"\x10network_tx_bytes\x18\v \x01(\x04R\x0enetworkTxBytes\x12#\n" +
	"\rprocess_count\x18\f \x01(\x05R\fprocessCount\x12\x16\n" +
	"\x06uptime\x18\r \x01(\x04R\x06uptime\"\xfb\x03\n" +
	"\n" +
	"SystemInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x1d\n" +
	"\n" +
	"os_version\x18\x03 \x01(\tR\tosVersion\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12\"\n" +
	"\farchitecture\x18\x05 \x01(\tR\farchitecture\x12\x1b\n" +
	"\tcpu_model\x18\x06 \x01(\tR\bcpuModel\x12\x1b\n" +
	"\tcpu_cores\x18\a \x01(\x05R\bcpuCores\x12\x1f\n" +
	"\vcpu_threads\x18\b \x01(\x05R\n" +
	"cpuThreads\x12\x1b\n" +
	"\tcpu_speed\x18\t \x01(\x01R\bcpuSpeed\x12!\n" +
	"\ftotal_memory\x18\n" +
	" \x01(\x04R\vtotalMemory\x12-\n" +
	"\x03gpu\x18\v \x03(\v2\x1b.sentinel.dataplane.GPUInfoR\x03gpu\x129\n" +
	"\astorage\x18\f \x03(\v2\x1f.sentinel.dataplane.StorageInfoR\astorage\x12#\n" +
	"\rserial_number\x18\r \x01(\tR\fserialNumber\x12\"\n" +
	"\fmanufacturer\x18\x0e \x01(\tR\fmanufacturer\x12\x14\n" +
	"\x05model\x18\x0f \x01(\tR\x05model\"t\n" +
	"\aGPUInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06vendor\x18\x02 \x01(\tR\x06vendor\x12\x16\n" +
	"\x06memory\x18\x03 \x01(\x04R\x06memory\x12%\n" +
	"\x0edriver_version\x18\x04 \x01(\tR\rdriverVersion\"\xb6\x01\n" +
	"\vStorageInfo\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x1e\n" +
	"\n" +
	"mountpoint\x18\x02 \x01(\tR\n" +
	"mountpoint\x12\x17\n" +
	"\afs_type\x18\x03 \x01(\tR\x06fsType\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x04R\x05total\x12\x12\n" +
	"\x04used\x18\x05 \x01(\x04R\x04used\x12\x12\n" +
	"\x04free\x18\x06 \x01(\x04R\x04free\x12\x18\n" +
	"\apercent\x18\a \x01(\x01R\apercent\"\x82\x01\n" +
	"\x11InstalledSoftware\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1c\n" +
	"\tpublisher\x18\x03 \x01(\tR\tpublisher\x12!\n" +
	"\finstall_date\x18\x04 \x01(\tR\vinstallDate\"\xcc\x01\n" +
	"\rInventoryData\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12?\n" +
	"\vsystem_info\x18\x03 \x01(\v2\x1e.sentinel.dataplane.SystemInfoR\n" +
	"systemInfo\x12A\n" +
	"\bsoftware\x18\x04 \x03(\v2%.sentinel.dataplane.InstalledSoftwareR\bsoftware\"\x90\x02\n" +
	"\bLogEntry\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12F\n" +
	"\bmetadata\x18\x06 \x03(\v2*.sentinel.dataplane.LogEntry.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"]\n" +
	"\bLogBatch\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x126\n" +
	"\aentries\x18\x02 \x03(\v2\x1c.sentinel.dataplane.LogEntryR\aentries\"\xc6\x01\n" +
	"\tFileChunk\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x03R\x06offset\x12\x1d\n" +
	"\n" +
	"total_size\x18\x06 \x01(\x03R\ttotalSize\x12\x17\n" +
	"\ais_last\x18\a \x01(\bR\x06isLast\"\xd7\x01\n" +
	"\rBulkDataChunk\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1b\n" +
	"\tdata_type\x18\x03 \x01(\tR\bdataType\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x1f\n" +
	"\vchunk_index\x18\x05 \x01(\x05R\n" +
	"chunkIndex\x12!\n" +
	"\ftotal_chunks\x18\x06 \x01(\x05R\vtotalChunks\x12\x17\n" +
	"\ais_last\x18\a \x01(\bR\x06isLast\"@\n" +
	"\x0eStreamResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\a\n" +
	"\x05Empty2\xc7\x03\n" +
	"\x10DataPlaneService\x12R\n" +
	"\rStreamMetrics\x12\x1b.sentinel.dataplane.Metrics\x1a\".sentinel.dataplane.StreamResponse(\x01\x12X\n" +
	"\x0fUploadInventory\x12!.sentinel.dataplane.InventoryData\x1a\".sentinel.dataplane.StreamResponse\x12P\n" +
	"\n" +
	"StreamLogs\x12\x1c.sentinel.dataplane.LogBatch\x1a\".sentinel.dataplane.StreamResponse(\x01\x12X\n" +
	"\x11StreamFileContent\x12\x1d.sentinel.dataplane.FileChunk\x1a\".sentinel.dataplane.StreamResponse(\x01\x12Y\n" +
	"\x0eUploadBulkData\x12!.sentinel.dataplane.BulkDataChunk\x1a\".sentinel.dataplane.StreamResponse(\x01B3Z1github.com/sentinel/agent/internal/grpc/dataplaneb\x06proto3"

var (
	file_dataplane_proto_rawDescOnce sync.Once
	file_dataplane_proto_rawDescData []byte
)

func file_dataplane_proto_rawDescGZIP() []byte {
	file_dataplane_proto_rawDescOnce.Do(func() {
		file_dataplane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dataplane_proto_rawDesc), len(file_dataplane_proto_rawDesc)))
	})
	return file_dataplane_proto_rawDescData
}

var file_dataplane_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_dataplane_proto_goTypes = []any{
	(*Metrics)(nil),           // 0: sentinel.dataplane.Metrics
	(*SystemInfo)(nil),        // 1: sentinel.dataplane.SystemInfo
	(*GPUInfo)(nil),           // 2: sentinel.dataplane.GPUInfo
	(*StorageInfo)(nil),       // 3: sentinel.dataplane.StorageInfo
	(*InstalledSoftware)(nil), // 4: sentinel.dataplane.InstalledSoftware
	(*InventoryData)(nil),     // 5: sentinel.dataplane.InventoryData
	(*LogEntry)(nil),          // 6: sentinel.dataplane.LogEntry
	(*LogBatch)(nil),          // 7: sentinel.dataplane.LogBatch
	(*FileChunk)(nil),         // 8: sentinel.dataplane.FileChunk
	(*BulkDataChunk)(nil),     // 9: sentinel.dataplane.BulkDataChunk
	(*StreamResponse)(nil),    // 10: sentinel.dataplane.StreamResponse
	(*Empty)(nil),             // 11: sentinel.dataplane.Empty
	nil,                       // 12: sentinel.dataplane.LogEntry.MetadataEntry
}
var file_dataplane_proto_depIdxs = []int32{
	2,  // 0: sentinel.dataplane.SystemInfo.gpu:type_name -> sentinel.dataplane.GPUInfo
	3,  // 1: sentinel.dataplane.SystemInfo.storage:type_name -> sentinel.dataplane.StorageInfo
	1,  // 2: sentinel.dataplane.InventoryData.system_info:type_name -> sentinel.dataplane.SystemInfo
	4,  // 3: sentinel.dataplane.InventoryData.software:type_name -> sentinel.dataplane.InstalledSoftware
	12, // 4: sentinel.dataplane.LogEntry.metadata:type_name -> sentinel.dataplane.LogEntry.MetadataEntry
	6,  // 5: sentinel.dataplane.LogBatch.entries:type_name -> sentinel.dataplane.LogEntry
	0,  // 6: sentinel.dataplane.DataPlaneService.StreamMetrics:input_type -> sentinel.dataplane.Metrics
	5,  // 7: sentinel.dataplane.DataPlaneService.UploadInventory:input_type -> sentinel.dataplane.InventoryData
	7,  // 8: sentinel.dataplane.DataPlaneService.StreamLogs:input_type -> sentinel.dataplane.LogBatch
	8,  // 9: sentinel.dataplane.DataPlaneService.StreamFileContent:input_type -> sentinel.dataplane.FileChunk
	9,  // 10: sentinel.dataplane.DataPlaneService.UploadBulkData:input_type -> sentinel.dataplane.BulkDataChunk
	10, // 11: sentinel.dataplane.DataPlaneService.StreamMetrics:output_type -> sentinel.dataplane.StreamResponse
	10, // 12: sentinel.dataplane.DataPlaneService.UploadInventory:output_type -> sentinel.dataplane.StreamResponse
	10, // 13: sentinel.dataplane.DataPlaneService.StreamLogs:output_type -> sentinel.dataplane.StreamResponse
	10, // 14: sentinel.dataplane.DataPlaneService.StreamFileContent:output_type -> sentinel.dataplane.StreamResponse
	10, // 15: sentinel.dataplane.DataPlaneService.UploadBulkData:output_type -> sentinel.dataplane.StreamResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_dataplane_proto_init() }
func file_dataplane_proto_init() {
	if File_dataplane_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dataplane_proto_rawDesc), len(file_dataplane_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dataplane_proto_goTypes,
		DependencyIndexes: file_dataplane_proto_depIdxs,
		MessageInfos:      file_dataplane_proto_msgTypes,
	}.Build()
	File_dataplane_proto = out.File
	file_dataplane_proto_goTypes = nil
	file_dataplane_proto_depIdxs = nil
}
