// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: dataplane.proto

package dataplane

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataPlaneService_StreamMetrics_FullMethodName     = "/sentinel.dataplane.DataPlaneService/StreamMetrics"
	DataPlaneService_UploadInventory_FullMethodName   = "/sentinel.dataplane.DataPlaneService/UploadInventory"
	DataPlaneService_StreamLogs_FullMethodName        = "/sentinel.dataplane.DataPlaneService/StreamLogs"
	DataPlaneService_StreamFileContent_FullMethodName = "/sentinel.dataplane.DataPlaneService/StreamFileContent"
	DataPlaneService_UploadBulkData_FullMethodName    = "/sentinel.dataplane.DataPlaneService/UploadBulkData"
)

// DataPlaneServiceClient is the client API for DataPlaneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DataPlane service - Data streaming only, NO command execution
type DataPlaneServiceClient interface {
	// Metrics streaming (client-side streaming)
	// Agent continuously streams metrics to server
	StreamMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Metrics, StreamResponse], error)
	// Inventory upload (unary)
	// Agent uploads system inventory periodically
	UploadInventory(ctx context.Context, in *InventoryData, opts ...grpc.CallOption) (*StreamResponse, error)
	// Log streaming (client-side streaming)
	// Agent streams log batches to server
	StreamLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogBatch, StreamResponse], error)
	// File content streaming (client-side streaming)
	// Agent streams file content for downloads
	StreamFileContent(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, StreamResponse], error)
	// Bulk data upload (client-side streaming)
	// Agent uploads diagnostic data in chunks
	UploadBulkData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[BulkDataChunk, StreamResponse], error)
}

type dataPlaneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataPlaneServiceClient(cc grpc.ClientConnInterface) DataPlaneServiceClient {
	return &dataPlaneServiceClient{cc}
}

func (c *dataPlaneServiceClient) StreamMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Metrics, StreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataPlaneService_ServiceDesc.Streams[0], DataPlaneService_StreamMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Metrics, StreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataPlaneService_StreamMetricsClient = grpc.ClientStreamingClient[Metrics, StreamResponse]

func (c *dataPlaneServiceClient) UploadInventory(ctx context.Context, in *InventoryData, opts ...grpc.CallOption) (*StreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StreamResponse)
	err := c.cc.Invoke(ctx, DataPlaneService_UploadInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataPlaneServiceClient) StreamLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogBatch, StreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataPlaneService_ServiceDesc.Streams[1], DataPlaneService_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogBatch, StreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataPlaneService_StreamLogsClient = grpc.ClientStreamingClient[LogBatch, StreamResponse]

func (c *dataPlaneServiceClient) StreamFileContent(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, StreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataPlaneService_ServiceDesc.Streams[2], DataPlaneService_StreamFileContent_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileChunk, StreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataPlaneService_StreamFileContentClient = grpc.ClientStreamingClient[FileChunk, StreamResponse]

func (c *dataPlaneServiceClient) UploadBulkData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[BulkDataChunk, StreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataPlaneService_ServiceDesc.Streams[3], DataPlaneService_UploadBulkData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BulkDataChunk, StreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataPlaneService_UploadBulkDataClient = grpc.ClientStreamingClient[BulkDataChunk, StreamResponse]

// DataPlaneServiceServer is the server API for DataPlaneService service.
// All implementations must embed UnimplementedDataPlaneServiceServer
// for forward compatibility.
//
// DataPlane service - Data streaming only, NO command execution
type DataPlaneServiceServer interface {
	// Metrics streaming (client-side streaming)
	// Agent continuously streams metrics to server
	StreamMetrics(grpc.ClientStreamingServer[Metrics, StreamResponse]) error
	// Inventory upload (unary)
	// Agent uploads system inventory periodically
	UploadInventory(context.Context, *InventoryData) (*StreamResponse, error)
	// Log streaming (client-side streaming)
	// Agent streams log batches to server
	StreamLogs(grpc.ClientStreamingServer[LogBatch, StreamResponse]) error
	// File content streaming (client-side streaming)
	// Agent streams file content for downloads
	StreamFileContent(grpc.ClientStreamingServer[FileChunk, StreamResponse]) error
	// Bulk data upload (client-side streaming)
	// Agent uploads diagnostic data in chunks
	UploadBulkData(grpc.ClientStreamingServer[BulkDataChunk, StreamResponse]) error
	mustEmbedUnimplementedDataPlaneServiceServer()
}

// UnimplementedDataPlaneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataPlaneServiceServer struct{}

func (UnimplementedDataPlaneServiceServer) StreamMetrics(grpc.ClientStreamingServer[Metrics, StreamResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamMetrics not implemented")
}
func (UnimplementedDataPlaneServiceServer) UploadInventory(context.Context, *InventoryData) (*StreamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadInventory not implemented")
}
func (UnimplementedDataPlaneServiceServer) StreamLogs(grpc.ClientStreamingServer[LogBatch, StreamResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedDataPlaneServiceServer) StreamFileContent(grpc.ClientStreamingServer[FileChunk, StreamResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamFileContent not implemented")
}
func (UnimplementedDataPlaneServiceServer) UploadBulkData(grpc.ClientStreamingServer[BulkDataChunk, StreamResponse]) error {
	return status.Error(codes.Unimplemented, "method UploadBulkData not implemented")
}
func (UnimplementedDataPlaneServiceServer) mustEmbedUnimplementedDataPlaneServiceServer() {}
func (UnimplementedDataPlaneServiceServer) testEmbeddedByValue()                          {}

// UnsafeDataPlaneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataPlaneServiceServer will
// result in compilation errors.
type UnsafeDataPlaneServiceServer interface {
	mustEmbedUnimplementedDataPlaneServiceServer()
}

func RegisterDataPlaneServiceServer(s grpc.ServiceRegistrar, srv DataPlaneServiceServer) {
	// If the following call panics, it indicates UnimplementedDataPlaneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataPlaneService_ServiceDesc, srv)
}

func _DataPlaneService_StreamMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataPlaneServiceServer).StreamMetrics(&grpc.GenericServerStream[Metrics, StreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataPlaneService_StreamMetricsServer = grpc.ClientStreamingServer[Metrics, StreamResponse]

func _DataPlaneService_UploadInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InventoryData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataPlaneServiceServer).UploadInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataPlaneService_UploadInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataPlaneServiceServer).UploadInventory(ctx, req.(*InventoryData))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataPlaneService_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataPlaneServiceServer).StreamLogs(&grpc.GenericServerStream[LogBatch, StreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataPlaneService_StreamLogsServer = grpc.ClientStreamingServer[LogBatch, StreamResponse]

func _DataPlaneService_StreamFileContent_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataPlaneServiceServer).StreamFileContent(&grpc.GenericServerStream[FileChunk, StreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataPlaneService_StreamFileContentServer = grpc.ClientStreamingServer[FileChunk, StreamResponse]

func _DataPlaneService_UploadBulkData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataPlaneServiceServer).UploadBulkData(&grpc.GenericServerStream[BulkDataChunk, StreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataPlaneService_UploadBulkDataServer = grpc.ClientStreamingServer[BulkDataChunk, StreamResponse]

// DataPlaneService_ServiceDesc is the grpc.ServiceDesc for DataPlaneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataPlaneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sentinel.dataplane.DataPlaneService",
	HandlerType: (*DataPlaneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadInventory",
			Handler:    _DataPlaneService_UploadInventory_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMetrics",
			Handler:       _DataPlaneService_StreamMetrics_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamLogs",
			Handler:       _DataPlaneService_StreamLogs_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamFileContent",
			Handler:       _DataPlaneService_StreamFileContent_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "UploadBulkData",
			Handler:       _DataPlaneService_UploadBulkData_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "dataplane.proto",
}
