export { Login } from './Login';
export { Register } from './Register';
export { Dashboard } from './Dashboard';
export { Devices } from './Devices';
export { DeviceDetail } from './DeviceDetail';
export { Alerts } from './Alerts';
export { AlertRules } from './AlertRules';
export { Scripts } from './Scripts';
export { Settings } from './Settings';
export { Users } from './Users';
export { AgentDownloads } from './AgentDownloads';
export { default as InstallationPortal } from './InstallationPortal';
export { default as AgentInstallations } from './AgentInstallations';
